### ISSUE TITLE
otelzerolog/v0.1.x retraction status?

### ISSUE THREAD

**Issue by mgabeler-lee-6rs** [vincentfree/opentelemetry#72]
In dependency housekeeping for a project that uses this library, I noticed the update to v0.1.1, wherein the only change is the retraction of v0.1.0.

This feels suspicious of being a mistake, but I can't tell for sure?

**Comment by vincentfree** [comment]
My mistake was leaving debug code in my examples: https://github.com/vincentfree/opentelemetry/commit/ddd335b4aa3cb02b333d15c7643bc6e07b63279a

Since there is no way to update the just released library I found that leaving this in over doing a redaction with an update in the examples which are part of the user facing documentation and validation for this library were worth while.

It might not be a big deal for everyone but to me the documentation and examples are also quite important since beginning users tend to like working examples of the code. Sorry for it being confusing though. Hope this clears it up. 

I've tried to keep som backwards compatibility in but I'm moving away from using global variables for setting the default values used to using a struct of a Logger that embeds the `zerolog` logger. This to me is better since if you create multiple loggers, the config does not clash. In running tests I found that the global config can lead to errors. 

Hope this is clear to you and that it doesn't break your usage of the library.

**Comment by vincentfree** [comment]
One key change made is supporting the opentelemetry Log Bridge API implementation which should give you the ability to ship logs directly into a OTEL Collector without having to read the logs with an external tool like fluentbit etc. or ingest them from stdout or a file using receivers for them.

To me this is exactly what I want from a library like this. the integration to a collector wasn't provided yet and now it is :)

**Comment by mgabeler-lee-6rs** [comment]
Aah, the tag for v0.1.0 is at least now on the new commit, maybe it wasn't originally.

Anyways, this clarifies things, and the minor api breaks the changes introduce are ... minor, and easy to deal with, and accounted for in the semver bump so no worries there. I mostly just wanted to make sure something that wasn't "ready for release" hadn't been tagged by accident :)

FWIW, the one API break that impacts my usage was removing the global `func AddTracingContext`, but it's clear & easy even without having read the fine examples how to adapt my project to the new instance method.
